name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  e2e:
    uses: ./.github/workflows/reusable-e2e.yml

  npm-publish:
    needs: e2e
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Initialize Project
        run: |
          npm install
          npx lerna bootstrap
          npm run build

      - name: Compile Contracts
        run: |
          cd contracts
          npm run compileSol

      - name: Publish Project
        run: |
          # Prevent `git commit error` when running `lerna version`
          # It will not pushed to GitHub. It is ephemeral
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          lerna version 0.0.0-ci.$(git rev-parse --short HEAD) --no-push --yes
          lerna publish from-git --dist-tag ci --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
